# coding: utf-8

"""
    VAM-Data-Bridges

    API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern

<<<<<<< HEAD
    The version of the OpenAPI document: 4.1.0
=======
    The version of the OpenAPI document: 4.0.0
>>>>>>> dev
    Contact: wfp.economicanalysis@wfp.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from data_bridges_client.api.markets_api import MarketsApi


class TestMarketsApi(unittest.TestCase):
    """MarketsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarketsApi()

    def tearDown(self) -> None:
        pass

    def test_markets_geo_json_list_get(self) -> None:
        """Test case for markets_geo_json_list_get

        Provide a list of geo referenced markets in a specific country
        """
        pass

    def test_markets_list_get(self) -> None:
        """Test case for markets_list_get

        Get a complete list of markets in a country
        """
        pass

    def test_markets_markets_as_csv_get(self) -> None:
        """Test case for markets_markets_as_csv_get

        Get a complete list of markets in a country
        """
        pass

    def test_markets_nearby_markets_get(self) -> None:
        """Test case for markets_nearby_markets_get

        Find markets near a given location by longitude and latitude within a 15Km distance
        """
        pass


if __name__ == '__main__':
    unittest.main()
