"""
    VAM-Data-Bridges

    API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern  # noqa: E501

    The version of the OpenAPI document: 1.3.1
    Contact: wfp.economicanalysis@wfp.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import data_bridges_client
from data_bridges_client.api.currency_api import CurrencyApi  # noqa: E501


class TestCurrencyApi(unittest.TestCase):
    """CurrencyApi unit test stubs"""

    def setUp(self):
        self.api = CurrencyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_currency_list_get(self):
        """Test case for currency_list_get

        Returns the list of currencies available in the internal VAM database, with Currency 3-letter code, matching with ISO 4217.  # noqa: E501
        """
        pass

    def test_currency_usd_indirect_quotation_get(self):
        """Test case for currency_usd_indirect_quotation_get

        Returns the value of the Exchange rates from Trading Economics, for official rates, and DataViz for unofficial rates.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
