"""
    VAM-Data-Bridges

    API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern  # noqa: E501

    The version of the OpenAPI document: 1.3.1
    Contact: wfp.economicanalysis@wfp.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import data_bridges_client
from data_bridges_client.model.coordinate import Coordinate
from data_bridges_client.model.dimension import Dimension
from data_bridges_client.model.envelope import Envelope
from data_bridges_client.model.geometry_factory import GeometryFactory
from data_bridges_client.model.ogc_geometry_type import OgcGeometryType
from data_bridges_client.model.point import Point
from data_bridges_client.model.precision_model import PrecisionModel
globals()['Coordinate'] = Coordinate
globals()['Dimension'] = Dimension
globals()['Envelope'] = Envelope
globals()['GeometryFactory'] = GeometryFactory
globals()['OgcGeometryType'] = OgcGeometryType
globals()['Point'] = Point
globals()['PrecisionModel'] = PrecisionModel
from data_bridges_client.model.geometry import Geometry


class TestGeometry(unittest.TestCase):
    """Geometry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeometry(self):
        """Test Geometry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Geometry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
