NAME: 'analytics-integration-databridges'
VERSION : '4.1.0'
KEY: 'Hjo8WHWVGe5jicksTYgduPmTUEwa'
SECRET: 'JKL4BjVTG3J4LDYmSZRLCjKK84Ea'
# KEY3.0: '_9D8S4GtBnJoln7znAb0e8lGrVYa'
# SECRET3.0: 'nL73B6dAGmJ62dN53zO7NhWe5UYa'
SCOPES:
 - 'vamdatabridges_household-fulldata_get'
 - 'vamdatabridges_household-officialusebase_get'
 - 'vamdatabridges_household-publicbasedata_get'
 - 'vamdatabridges_commodities-categories-list_get'
 - 'vamdatabridges_commodities-list_get'
 - 'vamdatabridges_commodityunits-conversion-list_get'
 - 'vamdatabridges_commodityunits-list_get'
 - 'vamdatabridges_currency-list_get'
 - 'vamdatabridges_currency-usdindirectquotation_get'
 - 'vamdatabridges_economicdata-indicatorlist_get'
 - 'vamdatabridges_economicdata_get'
 - 'vamdatabridges_foodsecurity-list_get'
 - 'vamdatabridges_gorp-latest_get'
 - 'vamdatabridges_gorp-list_get'
 - 'vamdatabridges_household-surveys_get'
 - 'vamdatabridges_marketprices-alps_get'
 - 'vamdatabridges_marketprices-pricedaily_get'
 - 'vamdatabridges_marketprices-pricemonthly_get'
 - 'vamdatabridges_marketprices-priceweekly_get'
 - 'vamdatabridges_markets-geojsonlist_get'
 - 'vamdatabridges_markets-list_get'
 - 'vamdatabridges_markets-marketsascsv_get'
 - 'vamdatabridges_markets-nearbymarkets_get'
 - 'vamdatabridges_mfi-surveys-basedata_get'
 - 'vamdatabridges_mfi-surveys-fulldata_get'
 - 'vamdatabridges_mfi-surveys-processeddata_get'
 - 'vamdatabridges_mfi-surveys_get'
 - 'vamdatabridges_mfi-xlsforms_get'
  