{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "VAM-Data-Bridges",
    "description" : "API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) patte[...]",
    "contact" : {
      "name" : "VAM-INFO",
      "email" : "wfp.economicanalysis@wfp.org"
    },
    "version" : "5.0.0"
  },
  "servers" : [ {
    "url" : "https://api.wfp.org/vam-data-bridges/5.0.0"
  } ],
  "security" : [ {
    "default" : [ ]
  } ],
  "tags" : [ {
    "name" : "Aims",
    "description" : "The Asset Impact Monitoring from Space (AIMS) is a high-tech, data-driven, service that uses satellite \r\nimagery and landscape monitoring techniques to demonstrate and evaluate the impact of asset creation and livelihood programmes."
  }, {
    "name" : "Commodities",
    "description" : "Returns the list of commodities and their categories."
  }, {
    "name" : "CommodityUnits",
    "description" : "Returns the list of unit of measures and their conversion factors to standard quantities."
  }, {
    "name" : "Currency",
    "description" : "Returns official and, where available, unofficial exchange rates."
  }, {
    "name" : "EconomicData",
    "description" : "Returns the time series of values for different indicators. \r\nOriginal source is Trading Economics, licensed for redistribution only to the Vulnerability Analysis and Mapping - Economic and Market Analysis Unit."
  }, {
    "name" : "FoodSecurity",
    "description" : "IPC data"
  }, {
    "name" : "Gorp",
    "description" : "Number of acutely food insecure people in countries with WFP operational presence, in millions. \r\nSource is WFP’s Global Operational Response plan, numbers are updated with each publication (3 times a year). \r\nNumbers are updates to  WFP’s original estimate of COVID-19’s impact on acute food security conducted in June 2020 \r\n(see [https://docs.wfp.org/api/documents/WFP-0000128212/download/](https://docs.wfp.org/api/documents/WFP-0000128212/download/)). In the updates, [...]"
  }, {
    "name" : "Household",
    "description" : "Household Surveys"
  }, {
    "name" : "MarketPrices",
    "description" : "Returns time series of commodity market prices at different frequencies."
  }, {
    "name" : "Markets",
    "description" : "Returns the list of market locations with Administrative level codes matching with the VAM internal API."
  }, {
    "name" : "Rpme",
    "description" : "Retail Performance Monitoring and Evaluation"
  }, {
    "name" : "Surveys",
    "description" : "Market Functionality Index Surveys"
  }, {
    "name" : "XlsForms",
    "description" : "Market Functionality Index XLS Forms"
  } ],
  "paths" : {
    "/Aims/DownloadAllAnalysisRounds" : {
      "get" : {
        "tags" : [ "Incubation" ],
        "summary" : "Each asset has a baseline and several rounds. Each round reflects the number of times the asset \r\nhas been analysed over time. The number of total rounds changes according to the workstream: \r\nAsset Detection (AD) assets can have a total of 5 rounds, while there is no limit to the monitoring of \r\nLandscape Impact Assessment (LIA) assets. Assets considered for Site Prioritization (SP) have one round only. \r\nPlease note that adm0code can be obtained from https://api.va[...]",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Incubation-red)]()\n\n[![Generic badge](https://img.shields.io/badge/Access%20Policy-TEC_Architecture_+_Service_Owner_approvals_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Official%20Use%20Only-yellow)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_aims-downloadallanalysisrounds_get\"\n\n\n\n\n\n**Data Controller** - Wael ATT[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_aims-downloadallanalysisrounds_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Aims/DownloadPolygonFiles" : {
      "get" : {
        "tags" : [ "Incubation" ],
        "summary" : "Polygon files are available for Landscape Impact Assessment (LIA) assets only. \r\nThe file name corresponds to the “Geotrace” name. Please note that adm0code can be obtained \r\nfrom https://api.vam.wfp.org/geodata/swagger/index.html (VPN access only).",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Incubation-red)]()\n\n[![Generic badge](https://img.shields.io/badge/Access%20Policy-TEC_Architecture_+_Service_Owner_approvals_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Official%20Use%20Only-yellow)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_aims-downloadpolygonfiles_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_aims-downloadpolygonfiles_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Commodities/List" : {
      "get" : {
        "tags" : [ "Commodities" ],
        "summary" : "Provide the detailed list of the commodities available in DataBridges platform",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_commodities-list_get\"\n\nCOICOP 2018 codes are returned to hierarchically matching categories based on[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_commodities-list_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Commodities/Categories/List" : {
      "get" : {
        "tags" : [ "Commodities" ],
        "summary" : "Provides the list of categories.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_commodities-categories-list_get\"\n\nCategories are matched with high level WFP commodity classificatio[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_commodities-categories-list_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/CommodityUnits/List" : {
      "get" : {
        "tags" : [ "CommodityUnits" ],
        "summary" : "Provides the detailed list of the unit of measure available in DataBridges platform",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_commodityunits-list_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - [...]",
        "security" : [ {
          "default" : [ "vamdatabridges_commodityunits-list_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/CommodityUnits/Conversion/List" : {
      "get" : {
        "tags" : [ "CommodityUnits" ],
        "summary" : "Provides conversion factors to Kilogram or Litres for each convertible unit of measure.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_commodityunits-conversion-list_get\"\n\nSome non-standard units of measure might have different a conve[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_commodityunits-conversion-list_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Currency/List" : {
      "get" : {
        "tags" : [ "Currency" ],
        "summary" : "Returns the list of currencies available in the internal VAM database, with Currency 3-letter code, matching with ISO 4217.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_currency-list_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - This e[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_currency-list_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Currency/UsdIndirectQuotation" : {
      "get" : {
        "tags" : [ "Currency" ],
        "summary" : "Returns the value of the Exchange rates from Trading Economics, for official rates, and DataViz for unofficial rates.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_currency-usdindirectquotation_get\"\n\nReturns the time series of values of the Exchange rate of the Lo[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_currency-usdindirectquotation_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/EconomicData/{indicatorName}" : {
      "get" : {
        "tags" : [ "EconomicData" ],
        "summary" : "Returns the time series of values for different indicators.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_economicdata_get\"\n\nIndicator name as retrieved from /EconomicData/IndicatorList is mandatory.\n\n\n\[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_economicdata_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/EconomicData/IndicatorList" : {
      "get" : {
        "tags" : [ "EconomicData" ],
        "summary" : "Returns the lists of indicators.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_economicdata-indicatorlist_get\"\n\nReturns the lists of indicators for which Vulnerability Analysis an[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_economicdata-indicatorlist_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/FoodSecurity/List" : {
      "get" : {
        "tags" : [ "FoodSecurity" ],
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_foodsecurity-list_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - Th[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_foodsecurity-list_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Gorp/List" : {
      "get" : {
        "tags" : [ "Gorp" ],
        "summary" : "Return the full dataset of number of acutely food insecure (in millions) based on WFP Global Operational Response Plan.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_gorp-list_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - This endpo[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_gorp-list_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Gorp/Latest" : {
      "get" : {
        "tags" : [ "Gorp" ],
        "summary" : "Return the latest dataset of number of acutely food insecure (in millions)  based on WFP Global Operational Response Plan.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_gorp-latest_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - This end[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_gorp-latest_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Gorp/CountryLatest" : {
      "get" : {
        "tags" : [ "Gorp" ],
        "summary" : "Return the latest country dataset of number of acutely food insecure (in thousands)  based on WFP Global Operational Response Plan.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_gorp-countrylatest_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - T[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_gorp-countrylatest_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Gorp/RegionalLatest" : {
      "get" : {
        "tags" : [ "Gorp" ],
        "summary" : "Return the latest regional dataset of number of acutely food insecure (in millions)  based on WFP Global Operational Response Plan.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_gorp-regionallatest_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - [...]",
        "security" : [ {
          "default" : [ "vamdatabridges_gorp-regionallatest_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Gorp/GlobalLatest" : {
      "get" : {
        "tags" : [ "Gorp" ],
        "summary" : "Return the latest global dataset of number of acutely food insecure (in millions)  based on WFP Global Operational Response Plan.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_gorp-globallatest_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - Th[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_gorp-globallatest_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Household/Surveys" : {
      "get" : {
        "tags" : [ "Incubation" ],
        "summary" : "Retrieve 1) Survey IDs, 2) their corresponding XLS Form IDs, and 3) Base XLS Form of all household surveys conducted in a country. \r\nA date of reference, SurveyDate, for the data collection is set by the officer responsible for the upload for each survey.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Incubation-red)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_household-surveys_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - This endpoin[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_household-surveys_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Household/FullData" : {
      "get" : {
        "tags" : [ "Incubation" ],
        "summary" : "Get a full dataset that includes all the fields included in the survey in addition to the core household fields by Survey ID.\r\nTo access this data, please contact Wael ATTIA for authorization. \r\nThis endpoint will send you only data you have access to, based on permissions assigned to your application profile. \r\nThe \"apiKey\" can be found in the profile section of the DataBridges application.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Incubation-red)]()\n\n[![Generic badge](https://img.shields.io/badge/Access%20Policy-TEC_Architecture_+_Service_Owner_approvals_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Official%20Use%20Only-yellow)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_household-fulldata_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API [...]",
        "security" : [ {
          "default" : [ "vamdatabridges_household-fulldata_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Household/DraftInternalBaseData" : {
      "get" : {
        "tags" : [ "Incubation" ],
        "summary" : "Get data that includes the core household fields only by Survey ID.\r\nTo access this data, please contact Wael ATTIA for authorization. \r\nThis endpoint will send you only data you have access to, based on permissions assigned to your application profile. \r\nThe \"apiKey\" can be found in the profile section of the DataBridges application.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Incubation-red)]()\n\n[![Generic badge](https://img.shields.io/badge/Access%20Policy-TEC_Architecture_+_Service_Owner_approvals_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Official%20Use%20Only-yellow)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_household-draftinternalbasedata_get\"\n\n\n\n\n\n**Data Controller** - Wael AT[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_household-draftinternalbasedata_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Household/OfficialUseBaseData" : {
      "get" : {
        "tags" : [ "Incubation" ],
        "summary" : "Get data that includes the core household fields only by Survey ID",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Incubation-red)]()\n\n[![Generic badge](https://img.shields.io/badge/Access%20Policy-TEC_Architecture_+_Service_Owner_approvals_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Official%20Use%20Only-yellow)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_household-officialusebasedata_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTI[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_household-officialusebasedata_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Household/PublicBaseData" : {
      "get" : {
        "tags" : [ "Incubation" ],
        "summary" : "Get data that includes the core household fields only by Survey ID",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Incubation-red)]()\n\n[![Generic badge](https://img.shields.io/badge/Access%20Policy-TEC_Architecture_+_Service_Owner_approvals_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_household-publicbasedata_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integratio[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_household-publicbasedata_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/MarketPrices/PriceMonthly" : {
      "get" : {
        "tags" : [ "MarketPrices" ],
        "summary" : "Returns a monthly time series of commodity market prices.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_marketprices-pricemonthly_get\"\n\nThis is the lowest frequency available and the most complete data so[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_marketprices-pricemonthly_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/MarketPrices/PriceWeekly" : {
      "get" : {
        "tags" : [ "MarketPrices" ],
        "summary" : "Returns a weekly time series of commodity market prices.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_marketprices-priceweekly_get\"\n\nWeeks used as reference are the International Organization for Standa[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_marketprices-priceweekly_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/MarketPrices/PriceDaily" : {
      "get" : {
        "tags" : [ "MarketPrices" ],
        "summary" : "Returns a daily time series of commodity market prices.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_marketprices-pricedaily_get\"\n\nThis is the highest frequency available. Data is flagged according to [...]",
        "security" : [ {
          "default" : [ "vamdatabridges_marketprices-pricedaily_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/MarketPrices/PriceRaw" : {
      "get" : {
        "tags" : [ "MarketPrices" ],
        "summary" : "Returns original commodity market prices",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access%20Policy-TEC_Architecture_+_Service_Owner_approvals_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Official%20Use%20Only-yellow)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_marketprices-priceraw_get\"\n\nRestricted endpoint. Returns the orig[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_marketprices-priceraw_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/MarketPrices/Alps" : {
      "get" : {
        "tags" : [ "MarketPrices" ],
        "summary" : "Returns time series values of ALPS and PEWI.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_marketprices-alps_get\"\n\nReturns the full time series of the Alert for Price Spikes (ALPS) and the va[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_marketprices-alps_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Markets/GeoJSONList" : {
      "get" : {
        "tags" : [ "Markets" ],
        "summary" : "Provide a list of geo referenced markets in a specific country",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_markets-geojsonlist_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - [...]",
        "security" : [ {
          "default" : [ "vamdatabridges_markets-geojsonlist_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Markets/NearbyMarkets" : {
      "get" : {
        "tags" : [ "Markets" ],
        "summary" : "Find markets near a given location by longitude and latitude within a 15Km distance",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_markets-nearbymarkets_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** [...]",
        "security" : [ {
          "default" : [ "vamdatabridges_markets-nearbymarkets_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Markets/MarketsAsCSV" : {
      "get" : {
        "tags" : [ "Markets" ],
        "summary" : "Get a complete list of markets in a country",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_markets-marketsascsv_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** -[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_markets-marketsascsv_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Markets/List" : {
      "get" : {
        "tags" : [ "Markets" ],
        "summary" : "Get a complete list of markets in a country",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_markets-list_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - This en[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_markets-list_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Rpme/Variables" : {
      "get" : {
        "tags" : [ "Rpme" ],
        "summary" : "List of variables",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_rpme-variables_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - This [...]",
        "security" : [ {
          "default" : [ "vamdatabridges_rpme-variables_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Rpme/OutputValues" : {
      "get" : {
        "tags" : [ "Rpme" ],
        "summary" : "Processed values for each variable used in the assessments",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_rpme-outputvalues_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - Th[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_rpme-outputvalues_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Rpme/Surveys" : {
      "get" : {
        "tags" : [ "Rpme" ],
        "summary" : "Retrieve 1) Survey IDs, 2) their corresponding XLS Form IDs, and 3) Base XLS Form of all RPME surveys conducted in a country. The date of reference, SurveyDate, for the data collection is set by the officer responsible for the upload of each survey.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_rpme-surveys_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - This en[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_rpme-surveys_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Rpme/XLSForms" : {
      "get" : {
        "tags" : [ "Rpme" ],
        "summary" : "Get a complete list of XLS Forms uploaded on the RPME in a given period of data collection. This is the digital version of the questionnaire used during the data collection exercise.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_rpme-xlsforms_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - This e[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_rpme-xlsforms_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Rpme/FullData" : {
      "get" : {
        "tags" : [ "Rpme" ],
        "summary" : "Get a full dataset that includes all the fields included in the survey in addition to the core RPME fields by Survey ID.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access%20Policy-TEC_Architecture_+_Service_Owner_approvals_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Official%20Use%20Only-yellow)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_rpme-fulldata_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n*[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_rpme-fulldata_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/Rpme/BaseData" : {
      "get" : {
        "tags" : [ "Rpme" ],
        "summary" : "Get data that includes the core RPME fields only by Survey ID",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_rpme-basedata_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - This e[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_rpme-basedata_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/MFI/Surveys" : {
      "get" : {
        "tags" : [ "Surveys" ],
        "summary" : "Retrieve 1) Survey IDs, 2) their corresponding XLS Form IDs, and 3) Base XLS Form of all MFI surveys conducted in a country. \r\nA date of reference, SurveyDate, for the data collection is set by the officer responsible for the upload for each survey.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_mfi-surveys_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - This end[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_mfi-surveys_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/MFI/Surveys/ProcessedData" : {
      "get" : {
        "tags" : [ "Surveys" ],
        "summary" : "Get a MFI processed data in long format; levels indicate the data aggregation level 1) Normalized Score, 2) Trader Aggregate Score, \r\n3) Market Aggregate Score, 4) Trader Median, 5) Trader Mean, 6) Market Mean; each line corresponds to one of the nine dimensions of scores \r\nplus the final MFI aggregate score; 1) Assortment, 2) Availability, 3) Price, 4) Resilience, 5) Competition, 6) Infrastructure, 7) Service, \r\n8) Quality, 9) Access and Protection, and 10) MFI final [...]",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_mfi-surveys-processeddata_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Patter[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_mfi-surveys-processeddata_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/MFI/Surveys/FullData" : {
      "get" : {
        "tags" : [ "Surveys" ],
        "summary" : "Get a full dataset that includes all the fields included in the survey in addition to the core Market Functionality Index (MFI) fields by Survey ID. To access this data, please contact global.mfi@wfp.org for authorization.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access%20Policy-TEC_Architecture_+_Service_Owner_approvals_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Official%20Use%20Only-yellow)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_mfi-surveys-fulldata_get\"\n\n\n\n\n\n**Data Controller** - Wael ATT[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_mfi-surveys-fulldata_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/MFI/Surveys/BaseData" : {
      "get" : {
        "tags" : [ "Surveys" ],
        "summary" : "Get data that includes the core Market Functionality Index (MFI) fields only by Survey ID",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_mfi-surveys-basedata_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** -[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_mfi-surveys-basedata_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/MFI/XlsForms" : {
      "get" : {
        "tags" : [ "XlsForms" ],
        "summary" : "Get a complete list of XLS Forms uploaded on the MFI Data Bridge in a given period of data collection. This is the digital version of the questionnaire used during the data collection exercise.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_mfi-xlsforms_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - This en[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_mfi-xlsforms_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    },
    "/XlsForms/definition" : {
      "get" : {
        "tags" : [ "Incubation" ],
        "summary" : "Get a complete set of XLS Form definitions of a given XLS Form ID. This is the digital version of the questionnaire used during the data collection exercise.",
        "description" : "\n\n[![Generic badge](https://img.shields.io/badge/Maturity%20Level-Incubation-red)]()\n\n[![Generic badge](https://img.shields.io/badge/Access_Policy-TEC_Architecture_approval_required-yellow)]()\n\n[![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()\n\n### This endpoint is restricted, it requires the scope: \"vamdatabridges_xlsforms-definition_get\"\n\n\n\n\n\n**Data Controller** - Wael ATTIA\n\n**API Integration Pattern** - This endpo[...]",
        "security" : [ {
          "default" : [ "vamdatabridges_xlsforms-definition_get" ]
        } ],
        "x-auth-type" : "Application & Application User",
        "x-throttling-tier" : "Unlimited"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "default" : {
        "type" : "oauth2",
        "flows" : {
          "implicit" : {
            "authorizationUrl" : "https://api.wfp.org/authorize",
            "scopes" : {
              "vamdatabridges_rpme-fulldata_get" : "vamdatabridges_rpme-fulldata_get",
              "vamdatabridges_foodsecurity-list_get" : "vamdatabridges_foodsecurity-list_get",
              "vamdatabridges_commodities-list_get" : "vamdatabridges_commodities-list_get",
              "vamdatabridges_commodityunits-list_get" : "vamdatabridges_commodityunits-list_get",
              "vamdatabridges_markets-nearbymarkets_get" : "vamdatabridges_markets-nearbymarkets_get",
              "vamdatabridges_rpme-outputvalues_get" : "vamdatabridges_rpme-outputvalues_get",
              "vamdatabridges_marketprices-alps_get" : "vamdatabridges_marketprices-alps_get",
              "vamdatabridges_mfi-surveys_get" : "vamdatabridges_mfi-surveys_get",
              "vamdatabridges_commodities-categories-list_get" : "vamdatabridges_commodities-categories-list_get",
              "vamdatabridges_commodityunits-conversion-list_get" : "vamdatabridges_commodityunits-conversion-list_get",
              "vamdatabridges_economicdata_get" : "vamdatabridges_economicdata_get",
              "vamdatabridges_mfi-surveys-processeddata_get" : "vamdatabridges_mfi-surveys-processeddata_get",
              "vamdatabridges_marketprices-priceweekly_get" : "vamdatabridges_marketprices-priceweekly_get",
              "vamdatabridges_markets-marketsascsv_get" : "vamdatabridges_markets-marketsascsv_get",
              "vamdatabridges_household-publicbasedata_get" : "vamdatabridges_household-publicbasedata_get",
              "vamdatabridges_gorp-globallatest_get" : "vamdatabridges_gorp-globallatest_get",
              "vamdatabridges_mfi-xlsforms_get" : "vamdatabridges_mfi-xlsforms_get",
              "vamdatabridges_economicdata-indicatorlist_get" : "vamdatabridges_economicdata-indicatorlist_get",
              "vamdatabridges_markets-geojsonlist_get" : "vamdatabridges_markets-geojsonlist_get",
              "vamdatabridges_gorp-regionallatest_get" : "vamdatabridges_gorp-regionallatest_get",
              "vamdatabridges_rpme-surveys_get" : "vamdatabridges_rpme-surveys_get",
              "vamdatabridges_rpme-xlsforms_get" : "vamdatabridges_rpme-xlsforms_get",
              "vamdatabridges_mfi-surveys-basedata_get" : "vamdatabridges_mfi-surveys-basedata_get",
              "vamdatabridges_mfi-surveys-fulldata_get" : "vamdatabridges_mfi-surveys-fulldata_get",
              "vamdatabridges_household-fulldata_get" : "vamdatabridges_household-fulldata_get",
              "vamdatabridges_household-officialusebasedata_get" : "vamdatabridges_household-officialusebasedata_get",
              "vamdatabridges_marketprices-pricemonthly_get" : "vamdatabridges_marketprices-pricemonthly_get",
              "vamdatabridges_aims-downloadallanalysisrounds_get" : "vamdatabridges_aims-downloadallanalysisrounds_get",
              "vamdatabridges_markets-list_get" : "vamdatabridges_markets-list_get",
              "vamdatabridges_currency-list_get" : "vamdatabridges_currency-list_get",
              "vamdatabridges_gorp-list_get" : "vamdatabridges_gorp-list_get",
              "vamdatabridges_marketprices-priceraw_get" : "vamdatabridges_marketprices-priceraw_get",
              "vamdatabridges_rpme-variables_get" : "vamdatabridges_rpme-variables_get",
              "vamdatabridges_aims-downloadpolygonfiles_get" : "vamdatabridges_aims-downloadpolygonfiles_get",
              "vamdatabridges_gorp-latest_get" : "vamdatabridges_gorp-latest_get",
              "vamdatabridges_gorp-countrylatest_get" : "vamdatabridges_gorp-countrylatest_get",
              "vamdatabridges_currency-usdindirectquotation_get" : "vamdatabridges_currency-usdindirectquotation_get",
              "vamdatabridges_xlsforms-definition_get" : "vamdatabridges_xlsforms-definition_get",
              "vamdatabridges_household-draftinternalbasedata_get" : "vamdatabridges_household-draftinternalbasedata_get",
              "vamdatabridges_household-surveys_get" : "vamdatabridges_household-surveys_get",
              "vamdatabridges_marketprices-pricedaily_get" : "vamdatabridges_marketprices-pricedaily_get",
              "vamdatabridges_rpme-basedata_get" : "vamdatabridges_rpme-basedata_get"
            },
            "x-scopes-bindings" : {
              "vamdatabridges_rpme-fulldata_get" : "vamdatabridges_rpme-fulldata_get",
              "vamdatabridges_foodsecurity-list_get" : "vamdatabridges_foodsecurity-list_get",
              "vamdatabridges_commodities-list_get" : "vamdatabridges_commodities-list_get",
              "vamdatabridges_commodityunits-list_get" : "vamdatabridges_commodityunits-list_get",
              "vamdatabridges_markets-nearbymarkets_get" : "vamdatabridges_markets-nearbymarkets_get",
              "vamdatabridges_rpme-outputvalues_get" : "vamdatabridges_rpme-outputvalues_get",
              "vamdatabridges_marketprices-alps_get" : "vamdatabridges_marketprices-alps_get",
              "vamdatabridges_mfi-surveys_get" : "vamdatabridges_mfi-surveys_get",
              "vamdatabridges_commodities-categories-list_get" : "vamdatabridges_commodities-categories-list_get",
              "vamdatabridges_commodityunits-conversion-list_get" : "vamdatabridges_commodityunits-conversion-list_get",
              "vamdatabridges_economicdata_get" : "vamdatabridges_economicdata_get",
              "vamdatabridges_mfi-surveys-processeddata_get" : "vamdatabridges_mfi-surveys-processeddata_get",
              "vamdatabridges_marketprices-priceweekly_get" : "vamdatabridges_marketprices-priceweekly_get",
              "vamdatabridges_markets-marketsascsv_get" : "vamdatabridges_markets-marketsascsv_get",
              "vamdatabridges_household-publicbasedata_get" : "vamdatabridges_household-publicbasedata_get",
              "vamdatabridges_gorp-globallatest_get" : "vamdatabridges_gorp-globallatest_get",
              "vamdatabridges_mfi-xlsforms_get" : "vamdatabridges_mfi-xlsforms_get",
              "vamdatabridges_economicdata-indicatorlist_get" : "vamdatabridges_economicdata-indicatorlist_get",
              "vamdatabridges_markets-geojsonlist_get" : "vamdatabridges_markets-geojsonlist_get",
              "vamdatabridges_gorp-regionallatest_get" : "vamdatabridges_gorp-regionallatest_get",
              "vamdatabridges_rpme-surveys_get" : "vamdatabridges_rpme-surveys_get",
              "vamdatabridges_rpme-xlsforms_get" : "vamdatabridges_rpme-xlsforms_get",
              "vamdatabridges_mfi-surveys-basedata_get" : "vamdatabridges_mfi-surveys-basedata_get",
              "vamdatabridges_mfi-surveys-fulldata_get" : "vamdatabridges_mfi-surveys-fulldata_get",
              "vamdatabridges_household-fulldata_get" : "vamdatabridges_household-fulldata_get",
              "vamdatabridges_household-officialusebasedata_get" : "vamdatabridges_household-officialusebasedata_get",
              "vamdatabridges_marketprices-pricemonthly_get" : "vamdatabridges_marketprices-pricemonthly_get",
              "vamdatabridges_aims-downloadallanalysisrounds_get" : "vamdatabridges_aims-downloadallanalysisrounds_get",
              "vamdatabridges_markets-list_get" : "vamdatabridges_markets-list_get",
              "vamdatabridges_currency-list_get" : "vamdatabridges_currency-list_get",
              "vamdatabridges_gorp-list_get" : "vamdatabridges_gorp-list_get",
              "vamdatabridges_marketprices-priceraw_get" : "vamdatabridges_marketprices-priceraw_get",
              "vamdatabridges_rpme-variables_get" : "vamdatabridges_rpme-variables_get",
              "vamdatabridges_aims-downloadpolygonfiles_get" : "vamdatabridges_aims-downloadpolygonfiles_get",
              "vamdatabridges_gorp-latest_get" : "vamdatabridges_gorp-latest_get",
              "vamdatabridges_gorp-countrylatest_get" : "vamdatabridges_gorp-countrylatest_get",
              "vamdatabridges_currency-usdindirectquotation_get" : "vamdatabridges_currency-usdindirectquotation_get",
              "vamdatabridges_xlsforms-definition_get" : "vamdatabridges_xlsforms-definition_get",
              "vamdatabridges_household-draftinternalbasedata_get" : "vamdatabridges_household-draftinternalbasedata_get",
              "vamdatabridges_household-surveys_get" : "vamdatabridges_household-surveys_get",
              "vamdatabridges_marketprices-pricedaily_get" : "vamdatabridges_marketprices-pricedaily_get",
              "vamdatabridges_rpme-basedata_get" : "vamdatabridges_rpme-basedata_get"
            }
          }
        }
      }
    }
  },
  "x-changelog" : [ {
    "changes" : "First release",
    "version" : "1.0.0"
  }, {
    "changes" : "\n*What's New*:\n\n- GET _/Commodities/Categories/List_\n- GET _/Commodities/List_\n- GET _/CommodityUnits/Conversion/List_\n- GET _/CommodityUnits/List_\n- GET _/Currency/List_\n- GET _/Currency/UsdIndirectQuotation_\n- GET _/EconomicData/IndicatorList_\n- GET _/EconomicData/{indicatorName}_\n- GET _/MarketPrices/Alps_\n- GET _/MarketPrices/PriceDaily_\n- GET _/MarketPrices/PriceMonthly_\n- GET _/MarketPrices/PriceRaw_\n- GET _/MarketPrices/PriceWeekly_\n- GET _/Markets/List_\n[...]",
    "version" : "1.1.0"
  }, {
    "changes" : "\n*What's New*:\n\n- GET /Gorp/Latest\n- GET /Gorp/List\n",
    "version" : "1.2.0"
  }, {
    "changes" : "\n*What's New*:\n\n- GET /FoodSecurity/List\n- GET /Rpme/OutputValues\n- GET /Rpme/Surveys\n- GET /Rpme/Variables\n- GET /Rpme/XLSForms",
    "version" : "1.3.0"
  }, {
    "changes" : "\n*What's Changed*:\n\n- Rpme/OutputValues response schema\n- /Rpme/* and /FoodSecurity/List maturity level to production-ready",
    "version" : "1.3.1"
  }, {
    "changes" : "\n*What's Changed*:\n- Changed response schema in GET /MFI/Surveys/BaseData \n- Changed response schema in GET /MFI/Surveys/FullData \n- Changed response schema in GET /MFI/XlsForms/definition \n- Changed response schema in GET /Markets/NearbyMarkets \n- Changed response schema in GET /Currency/List \n- Changed response schema in GET /Currency/UsdIndirectQuotation \n- Changed response schema in GET /FoodSecurity/List \n- Changed response schema in GET /Gorp/Latest \n- Changed re[...]",
    "version" : "1.3.3"
  }, {
    "changes" : "\n*What's New*:\n- GET /Household/Surveys\n- GET /Household/FullData\n- GET /Household/DraftInternalBaseData\n- GET /Household/OfficialUseBaseData\n- GET /Household/PublicBaseData\n- GET /Rpme/FullData\n- GET /Rpme/BaseData\n*What's Changed*:\n- Changed summary in GET /MFI/Surveys \n- Changed summary in GET /MFI/Surveys/ProcessedData \n- Changed description in GET /MarketPrices/PriceDaily \n",
    "version" : "1.4.0"
  }, {
    "changes" : "\n*This version is not backward-compatible with previous versions.*\n*What's Changed*:\n- Changed response schema in GET /MFI/XlsForms (Non-backward compatible)\n- Changed response schema in GET /Markets/GeoJSONList (Non-backward compatible)\n- Changed response schema in GET /Markets/List (Non-backward compatible)\n- GET /Markets/MarketsAsCSV \n- Changed response schema in GET /Rpme/XLSForms (Non-backward compatible)\n- Changed response schema in GET /EconomicData/{indicatorName[...]",
    "version" : "2.0.0"
  }, {
    "changes" : "\n*This version is not backward-compatible with previous versions.*\n*What's Changed*:\n- Add access scope to GET /Markets/MarketsAsCSV (Non-backward compatible)\n- Add access scope to GET /MFI/Surveys/BaseData (Non-backward compatible)\n- Add access scope to GET /MFI/XlsForms/definition (Non-backward compatible)\n- Add access scope to GET /Markets/NearbyMarkets (Non-backward compatible)\n- Add access scope to GET /Rpme/BaseData (Non-backward compatible)\n- Add access scope to G[...]",
    "version" : "3.0.0"
  }, {
    "changes" : "\n*This version is not backward-compatible with previous versions.*\n*What's New*:\n- GET /XlsForms/definition\n*What's Deleted*:\n- GET /MFI/XlsForms/definition\n*What's Changed*:\n- Added _pageSize_ query parameter to GET /Household/DraftInternalBaseData \n- Added _pageSize_ query parameter to GET /Household/FullData \n- Added _pageSize_ query parameter to GET /Household/OfficialUseBaseData \n- Added _pageSize_ query parameter to GET /Household/PublicBaseData \n- Added _pageSi[...]",
    "version" : "4.0.0"
  }, {
    "changes" : "\n*What's New*:\n- GET /Aims/DownloadAllAnalysisRounds\n- GET /Aims/DownloadPolygonFiles\n- GET /Gorp/CountryLatest\n- GET /Gorp/RegionalLatest\n- GET /Gorp/GlobalLatest\n*What's Changed*:\n- Minor changes to descriptions\n",
    "version" : "4.1.0"
  }, {
    "changes" : "\n*What's Changed*:\n- Changed response schema and added _apiKey_ query parameter to GET /Household/DraftInternalBaseData (Non-backward compatible)\n- Changed response schema and added _apiKey_ query parameter to GET /Household/FullData (Non-backward compatible)\n- Changed response schema and added _surveyId_ query parameter to GET /Household/Surveys \n- Minor changes to summaries\n",
    "version" : "5.0.0"
  } ]
}