"""
    VAM-Data-Bridges

    API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: wfp.economicanalysis@wfp.org
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from data_bridges_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from data_bridges_client.exceptions import ApiAttributeError


def lazy_import():
    from data_bridges_client.model.key_name_dto import KeyNameDto
    globals()['KeyNameDto'] = KeyNameDto


class HouseholdSurveyListDTO(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
        ('survey_original_filename',): {
            'max_length': 256,
            'min_length': 0,
        },
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'survey_id': (int,),  # noqa: E501
            'survey_status_id': (int,),  # noqa: E501
            'survey_start_date': (datetime, none_type,),  # noqa: E501
            'survey_end_date': (datetime, none_type,),  # noqa: E501
            'survey_create_date': (datetime,),  # noqa: E501
            'survey_validation_report': (str, none_type,),  # noqa: E501
            'survey_original_filename': (str, none_type,),  # noqa: E501
            'xls_form_name': (str, none_type,),  # noqa: E501
            'base_xls_form_name': (str, none_type,),  # noqa: E501
            'country_name': (str, none_type,),  # noqa: E501
            'adm0_code': (int,),  # noqa: E501
            'iso3_alpha3': (str, none_type,),  # noqa: E501
            'user_name': (str, none_type,),  # noqa: E501
            'approved_by': (str, none_type,),  # noqa: E501
            'original_csv_file': (str, none_type,),  # noqa: E501
            'base_data': (str, none_type,),  # noqa: E501
            'survey_attributes': ([KeyNameDto], none_type,),  # noqa: E501
            'organizations': ([KeyNameDto], none_type,),  # noqa: E501
            'survey_modality_name': (str, none_type,),  # noqa: E501
            'survey_category_name': (str, none_type,),  # noqa: E501
            'survey_sub_category_name': (str, none_type,),  # noqa: E501
            'survey_phase_name': (str, none_type,),  # noqa: E501
            'survey_visibilty': (str, none_type,),  # noqa: E501
            'is_continuous_monitoring': (bool,),  # noqa: E501
            'survey_name': (str, none_type,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'survey_id': 'surveyID',  # noqa: E501
        'survey_status_id': 'surveyStatusID',  # noqa: E501
        'survey_start_date': 'surveyStartDate',  # noqa: E501
        'survey_end_date': 'surveyEndDate',  # noqa: E501
        'survey_create_date': 'surveyCreateDate',  # noqa: E501
        'survey_validation_report': 'surveyValidationReport',  # noqa: E501
        'survey_original_filename': 'surveyOriginalFilename',  # noqa: E501
        'xls_form_name': 'xlsFormName',  # noqa: E501
        'base_xls_form_name': 'baseXlsFormName',  # noqa: E501
        'country_name': 'countryName',  # noqa: E501
        'adm0_code': 'adm0Code',  # noqa: E501
        'iso3_alpha3': 'iso3Alpha3',  # noqa: E501
        'user_name': 'userName',  # noqa: E501
        'approved_by': 'approvedBy',  # noqa: E501
        'original_csv_file': 'originalCsvFile',  # noqa: E501
        'base_data': 'baseData',  # noqa: E501
        'survey_attributes': 'surveyAttributes',  # noqa: E501
        'organizations': 'organizations',  # noqa: E501
        'survey_modality_name': 'surveyModalityName',  # noqa: E501
        'survey_category_name': 'surveyCategoryName',  # noqa: E501
        'survey_sub_category_name': 'surveySubCategoryName',  # noqa: E501
        'survey_phase_name': 'surveyPhaseName',  # noqa: E501
        'survey_visibilty': 'surveyVisibilty',  # noqa: E501
        'is_continuous_monitoring': 'isContinuousMonitoring',  # noqa: E501
        'survey_name': 'surveyName',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """HouseholdSurveyListDTO - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            survey_id (int): The Id of the Survey. [optional]  # noqa: E501
            survey_status_id (int): The Id of the Survey status. [optional]  # noqa: E501
            survey_start_date (datetime, none_type): The date when the survey has started. [optional]  # noqa: E501
            survey_end_date (datetime, none_type): The date when the survey has ended. [optional]  # noqa: E501
            survey_create_date (datetime): The date when the survey has been uploaded in the Data Bridges platform. [optional]  # noqa: E501
            survey_validation_report (str, none_type): The detailed report on the validation performed on the survey schema. [optional]  # noqa: E501
            survey_original_filename (str, none_type): The filename of the survey CSV file. [optional]  # noqa: E501
            xls_form_name (str, none_type): The name of the XLSForm used to collect data. [optional]  # noqa: E501
            base_xls_form_name (str, none_type): The name of the base XLSForm used to build the XLSForm. [optional]  # noqa: E501
            country_name (str, none_type): The name of the country where the survey has taken place. [optional]  # noqa: E501
            adm0_code (int): The internal code of the country where the survey has taken place. [optional]  # noqa: E501
            iso3_alpha3 (str, none_type): The ISO3 alpha code of the country where the survey has taken place. [optional]  # noqa: E501
            user_name (str, none_type): The name of the user that has uploaded the survey data. [optional]  # noqa: E501
            approved_by (str, none_type): [optional]  # noqa: E501
            original_csv_file (str, none_type): The link to download the original CSV file. [optional]  # noqa: E501
            base_data (str, none_type): The link to the JSON data reshaped on the base XLSForm. [optional]  # noqa: E501
            survey_attributes ([KeyNameDto], none_type): [optional]  # noqa: E501
            organizations ([KeyNameDto], none_type): [optional]  # noqa: E501
            survey_modality_name (str, none_type): [optional]  # noqa: E501
            survey_category_name (str, none_type): [optional]  # noqa: E501
            survey_sub_category_name (str, none_type): [optional]  # noqa: E501
            survey_phase_name (str, none_type): [optional]  # noqa: E501
            survey_visibilty (str, none_type): [optional]  # noqa: E501
            is_continuous_monitoring (bool): [optional]  # noqa: E501
            survey_name (str, none_type): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """HouseholdSurveyListDTO - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            survey_id (int): The Id of the Survey. [optional]  # noqa: E501
            survey_status_id (int): The Id of the Survey status. [optional]  # noqa: E501
            survey_start_date (datetime, none_type): The date when the survey has started. [optional]  # noqa: E501
            survey_end_date (datetime, none_type): The date when the survey has ended. [optional]  # noqa: E501
            survey_create_date (datetime): The date when the survey has been uploaded in the Data Bridges platform. [optional]  # noqa: E501
            survey_validation_report (str, none_type): The detailed report on the validation performed on the survey schema. [optional]  # noqa: E501
            survey_original_filename (str, none_type): The filename of the survey CSV file. [optional]  # noqa: E501
            xls_form_name (str, none_type): The name of the XLSForm used to collect data. [optional]  # noqa: E501
            base_xls_form_name (str, none_type): The name of the base XLSForm used to build the XLSForm. [optional]  # noqa: E501
            country_name (str, none_type): The name of the country where the survey has taken place. [optional]  # noqa: E501
            adm0_code (int): The internal code of the country where the survey has taken place. [optional]  # noqa: E501
            iso3_alpha3 (str, none_type): The ISO3 alpha code of the country where the survey has taken place. [optional]  # noqa: E501
            user_name (str, none_type): The name of the user that has uploaded the survey data. [optional]  # noqa: E501
            approved_by (str, none_type): [optional]  # noqa: E501
            original_csv_file (str, none_type): The link to download the original CSV file. [optional]  # noqa: E501
            base_data (str, none_type): The link to the JSON data reshaped on the base XLSForm. [optional]  # noqa: E501
            survey_attributes ([KeyNameDto], none_type): [optional]  # noqa: E501
            organizations ([KeyNameDto], none_type): [optional]  # noqa: E501
            survey_modality_name (str, none_type): [optional]  # noqa: E501
            survey_category_name (str, none_type): [optional]  # noqa: E501
            survey_sub_category_name (str, none_type): [optional]  # noqa: E501
            survey_phase_name (str, none_type): [optional]  # noqa: E501
            survey_visibilty (str, none_type): [optional]  # noqa: E501
            is_continuous_monitoring (bool): [optional]  # noqa: E501
            survey_name (str, none_type): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
